name: Python Bot

on: [push, pull_request]


jobs:
  run-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Code
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        run: python code_review.py

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "code_review.md"
          git commit -m "Save code review file."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           branch: ${{ github.ref }}